version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
      - image: circleci/mongo:4.4.1
    working_directory: ~/justin-proxy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  deploy:
    docker:
      - image: circleci/node:12.18.3
      - image: circleci/mongo:4.4.1
    steps:
      - run:
          name: Proxy-AWS EC2 Deploy-Development
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-218-144-168.us-east-2.compute.amazonaws.com \
            "echo Starting deployment && \
            cd ~/justin-proxy && \
            git checkout master && \
            git pull origin master && \
            npm install && \
            echo Deployment ending && \
            exit"
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
